name: ARM template deployment

on:
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Grouup rg-githubactions with azure CLI
        uses: Azure/cli@1.0.4
        with: 
          inlineScript: |
            az deployment sub --location "east uS" --template-file ./arm-templates/resoucegroup.json
      

 
