name: ARM template deployment

on:
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Two-way of executing an ARM template: Azure clie and /arm-deploy
      - name: Deploy Resource Group rg-githubactions with azure CLI
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment sub create --location "Australia East" --template-file ./arm-templates/resoucegroup.json

  #      - name: Deploy Resource Group rg-githubactions with arm-deploy
  #        uses: Azure/arm-deploy@v1
  #        with:
  #          scope: subscription
  #          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
  #          region: Australia East
  #          template: ./arm-templates/resoucegroup.json
  #          deploymentName: rg-githubactions
 
