name: Continuous Integration - Build Check

on:
  push:
    branches:
      - '*' # Run on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use the latest Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Build application
      run: |
        npm install
        npx webpack
